[project]
name = "my-time-manager"
version = "0.1.0"
description = "اپلیکیشن مدیریت زمان"
requires-python = ">=3.9"
dependencies = [
    "flet==0.28.3",
    "persian-datepicker"
]

[tool.flet]
org = "com.hmajd68"
product = "مدیریت زمان"

[tool.flet.app]
path = "src"

[tool.flet.android.permission]
"android.permission.POST_NOTIFICATIONS" = true
"android.permission.VIBRATE" = true